# This starter workflow is for a CMake project running on a single platform.
# This is taken from the default github workflow marketplace with minimal changes
name: C++ Build Test CI

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/cpp_ci.yaml"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip cmake
        curl -L 'https://github.com/libsdl-org/SDL/releases/download/release-3.2.4/SDL3-3.2.4.zip' -o SDL3-3.2.4.zip
        unzip SDL3-3.2.4.zip
        cd SDL3-3.2.4
        cmake -S . -B build
        cmake --build build
        sudo cmake --install build --prefix /usr/local

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # To be implemented
    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   run: ctest -C ${{env.BUILD_TYPE}}

