# This starter workflow is for a CMake project running on a single platform.
# This is taken from the default github workflow marketplace with minimal changes
name: C++ Build Test CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - name: Update System
      run: |
        sudo apt-get update
        sudo apt-get install wget

    - name: Install SDL2
      run: |
        sudo apt-get -y install libsdl2-dev

    - name: Install Catch2 v3
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        cmake -Bbuild -H.
        sudo cmake --build build --target install
        cd ../

    - name: Install nlohmann/json
      run: |
        sudo apt install nlohmann-json3-dev

    - name: Install Tetris ROM
      run: |
        mkdir ./roms
        cd roms && wget https://archive.org/download/tetris_gb/tetris.gb && cd ../

    - name: Build 
      run: |
        mkdir ./build
        bash ./build.sh

    - name: Test
      run: |
        bash ./build.sh -t
