name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - '.github/workflows/**'

# Add permissions block at the workflow level
permissions:
  contents: write

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags')
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Install dependencies
        run: |
          sudo apt update
          GIT_CLIFF_VERSION=$(curl -s "https://api.github.com/repos/orhun/git-cliff/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
          wget -qO git-cliff.tar.gz https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-$GIT_CLIFF_VERSION-x86_64-unknown-linux-gnu.tar.gz
          mkdir git-cliff-temp
          tar xf git-cliff.tar.gz --strip-components=1 -C git-cliff-temp
          sudo mv git-cliff-temp/git-cliff /usr/local/bin
          git cliff --version
          rm -rf git-cliff.tar.gz git-cliff-temp

      - name: Install project dependencies
        run: sudo apt install -y libsdl2-dev

      - name: Compile project
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Generate changelog
        run: |
          git cliff --init
          git-cliff -o CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: |
            ./build/ppGB

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
