# This starter workflow is for a CMake project running on a single platform.
# This is taken from the default github workflow marketplace with minimal changes
name: C++ Build Test CI

on:
  push:
    branches: [ "new-start" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update System
      run: |
        sudo apt-get update

    - name: Install SDL2
      run: |
        sudo apt-get -y install libsdl2-dev

    - name: Build and Test
      run: bash ./build.sh -t
